---
nginx_server:
  user: vagrant
  usergroup: vagrant
  default_config: "default.conf"

php_conf:
  xdebug_version: 2.5.5

mysql:
  root_passwd: root

openssl:
  csr_fields:
    country_name: ''
    locality_name: ''
    state_or_province_name: ''
    organization_name: ''
    organizational_unit_name: ''
    common_name: '*'
    email_address: 'email@youemail.com'

project:
  name: myproject
  domain:
    dev: '_'
  database:
    dbname: myproject
    user: myproject
    passwd: myproject
