---
ansible:
  requirements:
    - "python-pexpect"
    - "python-mysqldb"
    - "python-openssl"

system:
  timezone: UTC

nginx_server:
  user: vagrant
  usergroup: vagrant
  default_config: "default.conf"
